### ISSUE TITLE
Banner background color is invalid

### ISSUE THREAD

**Issue by danrabbit** [eudaldgr/elements#4] opened 2018-04-28 17:26 UTC
https://github.com/eudaldgr/elements/blob/1596ed738d34eb077a28be5119018b26f2e21302/data/com.github.eudaldgr.elements.appdata.xml#L46

There are some visual issues with the banner for this app in AppCenter because the background color here is invalid. The alpha value is between 0 and 1, not 0 and 256. It would be better to just drop the alpha value altogether and use `rgb(135, 203, 195)`

before:

![screenshot from 2018-04-28 10 26 52 2x](https://user-images.githubusercontent.com/7277719/39399217-ce9ba4ac-4ace-11e8-8914-7bb8a6b68057.png)

after:

![screenshot from 2018-04-28 10 27 13 2x](https://user-images.githubusercontent.com/7277719/39399219-d3513cfa-4ace-11e8-9847-7c6fbc21406d.png)

**Comment by eudaldgr** [comment] 2018-04-29 06:45
Thanks, I saw how bad the banner was in the AppCenter, but I did not know what the cause was.
In the next release it will be fixed.

**Closed by eudaldgr** 2018-04-29 06:45 UTC
